package Geometric_Lang.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myCanvas__BehaviorDescriptor = new Canvas__BehaviorDescriptor();
  private final BHDescriptor mySquare__BehaviorDescriptor = new Square__BehaviorDescriptor();
  private final BHDescriptor myShape__BehaviorDescriptor = new Shape__BehaviorDescriptor();
  private final BHDescriptor myCircle__BehaviorDescriptor = new Circle__BehaviorDescriptor();
  private final BHDescriptor myTriangle__BehaviorDescriptor = new Triangle__BehaviorDescriptor();
  private final BHDescriptor myRectangle__BehaviorDescriptor = new Rectangle__BehaviorDescriptor();
  private final BHDescriptor myParallelogram__BehaviorDescriptor = new Parallelogram__BehaviorDescriptor();
  private final BHDescriptor myRhombus__BehaviorDescriptor = new Rhombus__BehaviorDescriptor();
  private final BHDescriptor myTrapezium__BehaviorDescriptor = new Trapezium__BehaviorDescriptor();

  public BehaviorAspectDescriptor() {
  }

  @Nullable
  public BHDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return myCanvas__BehaviorDescriptor;
      case 1:
        return myCircle__BehaviorDescriptor;
      case 2:
        return myParallelogram__BehaviorDescriptor;
      case 3:
        return myRectangle__BehaviorDescriptor;
      case 4:
        return myRhombus__BehaviorDescriptor;
      case 5:
        return myShape__BehaviorDescriptor;
      case 6:
        return mySquare__BehaviorDescriptor;
      case 7:
        return myTrapezium__BehaviorDescriptor;
      case 8:
        return myTriangle__BehaviorDescriptor;
      default:
    }
    return null;
  }
  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648966883L), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5edL), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5b20f5bL), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b59aebffL), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5c11b6bL), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f239L), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5d24a94L), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5f2L)).seal();
}
