package Geometric_Lang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Area_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Canvas_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Circle_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Parallelogram_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Perimeter_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Rectangle_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new ShapeInfo_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new ShapeRef_Editor());
      case 8:
        return Collections.<ConceptEditor>singletonList(new Square_Editor());
      case 9:
        return Collections.<ConceptEditor>singletonList(new Trapezium_Editor());
      case 10:
        return Collections.<ConceptEditor>singletonList(new Triangle_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new ShapeRef_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983093L), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648966883L), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5edL), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5b20f5bL), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x216bb559e4e53a18L), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b59aebffL), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x216bb559e505dffeL), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f239L), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5d24a94L), MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5f2L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L)).seal();
}
