package Geometric_Lang.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.menus.substitute.SubstituteMenuBase;
import jetbrains.mps.lang.editor.menus.EditorMenuDescriptorBase;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.annotations.NotNull;
import java.util.List;
import jetbrains.mps.lang.editor.menus.MenuPart;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuItem;
import jetbrains.mps.openapi.editor.menus.substitute.SubstituteMenuContext;
import java.util.ArrayList;
import jetbrains.mps.lang.editor.menus.substitute.ConstraintsFilteringSubstituteMenuPartDecorator;
import jetbrains.mps.lang.editor.menus.substitute.ReferenceScopeSubstituteMenuPart;
import jetbrains.mps.lang.editor.menus.ConceptMenusPart;
import java.util.Collection;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.editor.menus.substitute.DefaultSubstituteMenuLookup;
import jetbrains.mps.smodel.language.LanguageRegistry;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class ShapeRef_SubstituteMenu extends SubstituteMenuBase {
  public ShapeRef_SubstituteMenu() {
    super(false, new EditorMenuDescriptorBase("default substitute menu for ShapeRef. Generated from implicit smart reference attribute.", new SNodePointer("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)", "4657511628476526743")));
  }
  @NotNull
  @Override
  protected List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> getParts(final SubstituteMenuContext _context) {
    List<MenuPart<SubstituteMenuItem, SubstituteMenuContext>> result = new ArrayList<MenuPart<SubstituteMenuItem, SubstituteMenuContext>>();
    result.add(new ConstraintsFilteringSubstituteMenuPartDecorator(new SMP_ReferenceScope_kqgijn_a(), CONCEPTS.ShapeRef$oD));
    result.add(new SMP_Subconcepts_kqgijn_b());
    return result;
  }

  public class SMP_ReferenceScope_kqgijn_a extends ReferenceScopeSubstituteMenuPart {

    public SMP_ReferenceScope_kqgijn_a() {
      super(CONCEPTS.ShapeRef$oD, LINKS.shape$qHkH, new EditorMenuDescriptorBase("reference scope substitute menu part", null));
    }

  }
  public class SMP_Subconcepts_kqgijn_b extends ConceptMenusPart<SubstituteMenuItem, SubstituteMenuContext> {
    public SMP_Subconcepts_kqgijn_b() {
      super(new EditorMenuDescriptorBase("include menus for all the direct subconcepts of " + "ShapeRef", null));
    }

    @Override
    protected Collection<SAbstractConcept> getConcepts(final SubstituteMenuContext _context) {
      return getDirectDescendants(_context, CONCEPTS.ShapeRef$oD);
    }

    @Override
    protected Collection<SubstituteMenuItem> createItemsForConcept(SubstituteMenuContext context, SAbstractConcept concept) {
      return context.createItems(new DefaultSubstituteMenuLookup(LanguageRegistry.getInstance(context.getEditorContext().getRepository()), concept));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ShapeRef$oD = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L, "Geometric_Lang.structure.ShapeRef");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink shape$qHkH = MetaAdapterFactory.getReferenceLink(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L, 0x40a2ce2648983098L, "shape");
  }
}
