package Geometric_Lang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptPresentationAspectBase;
import jetbrains.mps.smodel.runtime.ConceptPresentation;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.ConceptPresentationBuilder;

public class ConceptPresentationAspectImpl extends ConceptPresentationAspectBase {
  private ConceptPresentation props_Area;
  private ConceptPresentation props_Canvas;
  private ConceptPresentation props_Circle;
  private ConceptPresentation props_Function;
  private ConceptPresentation props_Parallelogram;
  private ConceptPresentation props_Perimeter;
  private ConceptPresentation props_Rectangle;
  private ConceptPresentation props_Rhombus;
  private ConceptPresentation props_Shape;
  private ConceptPresentation props_ShapeInfo;
  private ConceptPresentation props_ShapeRef;
  private ConceptPresentation props_Square;
  private ConceptPresentation props_Trapezium;
  private ConceptPresentation props_Triangle;

  @Override
  @Nullable
  public ConceptPresentation getDescriptor(SAbstractConcept c) {
    StructureAspectDescriptor structureDescriptor = (StructureAspectDescriptor) myLanguageRuntime.getAspect(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.class);
    switch (structureDescriptor.internalIndex(c)) {
      case LanguageConceptSwitch.Area:
        if (props_Area == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("area");
          props_Area = cpb.create();
        }
        return props_Area;
      case LanguageConceptSwitch.Canvas:
        if (props_Canvas == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Canvas = cpb.create();
        }
        return props_Canvas;
      case LanguageConceptSwitch.Circle:
        if (props_Circle == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Circle = cpb.create();
        }
        return props_Circle;
      case LanguageConceptSwitch.Function:
        if (props_Function == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Function = cpb.create();
        }
        return props_Function;
      case LanguageConceptSwitch.Parallelogram:
        if (props_Parallelogram == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Parallelogram = cpb.create();
        }
        return props_Parallelogram;
      case LanguageConceptSwitch.Perimeter:
        if (props_Perimeter == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("perimeter");
          props_Perimeter = cpb.create();
        }
        return props_Perimeter;
      case LanguageConceptSwitch.Rectangle:
        if (props_Rectangle == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Rectangle = cpb.create();
        }
        return props_Rectangle;
      case LanguageConceptSwitch.Rhombus:
        if (props_Rhombus == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Rhombus = cpb.create();
        }
        return props_Rhombus;
      case LanguageConceptSwitch.Shape:
        if (props_Shape == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          props_Shape = cpb.create();
        }
        return props_Shape;
      case LanguageConceptSwitch.ShapeInfo:
        if (props_ShapeInfo == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.rawPresentation("info");
          props_ShapeInfo = cpb.create();
        }
        return props_ShapeInfo;
      case LanguageConceptSwitch.ShapeRef:
        if (props_ShapeRef == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByReference(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L, 0x40a2ce2648983098L, "shape", "", "");
          props_ShapeRef = cpb.create();
        }
        return props_ShapeRef;
      case LanguageConceptSwitch.Square:
        if (props_Square == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Square = cpb.create();
        }
        return props_Square;
      case LanguageConceptSwitch.Trapezium:
        if (props_Trapezium == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Trapezium = cpb.create();
        }
        return props_Trapezium;
      case LanguageConceptSwitch.Triangle:
        if (props_Triangle == null) {
          ConceptPresentationBuilder cpb = new ConceptPresentationBuilder();
          cpb.presentationByName();
          props_Triangle = cpb.create();
        }
        return props_Triangle;
    }
    return null;
  }
}
