package Geometric_Lang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Area = 0;
  public static final int Canvas = 1;
  public static final int Circle = 2;
  public static final int Function = 3;
  public static final int Parallelogram = 4;
  public static final int Perimeter = 5;
  public static final int Rectangle = 6;
  public static final int Rhombus = 7;
  public static final int Shape = 8;
  public static final int ShapeInfo = 9;
  public static final int ShapeRef = 10;
  public static final int Square = 11;
  public static final int Trapezium = 12;
  public static final int Triangle = 13;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x943d70c59b264390L, 0xb8afcfbee654a2bcL);
    builder.put(0x40a2ce2648983093L, Area);
    builder.put(0x40a2ce2648966883L, Canvas);
    builder.put(0x40a2ce264896f5edL, Circle);
    builder.put(0x40a2ce2648983094L, Function);
    builder.put(0x57e16732b5b20f5bL, Parallelogram);
    builder.put(0x216bb559e4e53a18L, Perimeter);
    builder.put(0x57e16732b59aebffL, Rectangle);
    builder.put(0x57e16732b5c11b6bL, Rhombus);
    builder.put(0x40a2ce264896f23aL, Shape);
    builder.put(0x216bb559e505dffeL, ShapeInfo);
    builder.put(0x40a2ce2648983097L, ShapeRef);
    builder.put(0x40a2ce264896f239L, Square);
    builder.put(0x57e16732b5d24a94L, Trapezium);
    builder.put(0x40a2ce264896f5f2L, Triangle);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
