package Geometric_Lang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptArea = createDescriptorForArea();
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptFunction = createDescriptorForFunction();
  /*package*/ final ConceptDescriptor myConceptParallelogram = createDescriptorForParallelogram();
  /*package*/ final ConceptDescriptor myConceptPerimeter = createDescriptorForPerimeter();
  /*package*/ final ConceptDescriptor myConceptRectangle = createDescriptorForRectangle();
  /*package*/ final ConceptDescriptor myConceptRhombus = createDescriptorForRhombus();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptShapeInfo = createDescriptorForShapeInfo();
  /*package*/ final ConceptDescriptor myConceptShapeRef = createDescriptorForShapeRef();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  /*package*/ final ConceptDescriptor myConceptTrapezium = createDescriptorForTrapezium();
  /*package*/ final ConceptDescriptor myConceptTriangle = createDescriptorForTriangle();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, "jetbrains.mps.execution.util");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptArea, myConceptCanvas, myConceptCircle, myConceptFunction, myConceptParallelogram, myConceptPerimeter, myConceptRectangle, myConceptRhombus, myConceptShape, myConceptShapeInfo, myConceptShapeRef, myConceptSquare, myConceptTrapezium, myConceptTriangle);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Area:
        return myConceptArea;
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Function:
        return myConceptFunction;
      case LanguageConceptSwitch.Parallelogram:
        return myConceptParallelogram;
      case LanguageConceptSwitch.Perimeter:
        return myConceptPerimeter;
      case LanguageConceptSwitch.Rectangle:
        return myConceptRectangle;
      case LanguageConceptSwitch.Rhombus:
        return myConceptRhombus;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.ShapeInfo:
        return myConceptShapeInfo;
      case LanguageConceptSwitch.ShapeRef:
        return myConceptShapeRef;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      case LanguageConceptSwitch.Trapezium:
        return myConceptTrapezium;
      case LanguageConceptSwitch.Triangle:
        return myConceptTriangle;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForArea() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Area", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983093L);
    b.class_(false, false, false);
    b.parent(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983094L);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/4657511628476526739");
    b.version(3);
    b.aggregate("shape", 0x40a2ce2648983099L).target(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L).optional(false).ordered(true).multiple(false).origin("4657511628476526745").done();
    b.alias("area");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Canvas", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648966883L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/4657511628476409987");
    b.version(3);
    b.aggregate("shapes", 0x40a2ce2648a2686bL).target(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL).optional(true).ordered(true).multiple(true).origin("4657511628477196395").done();
    b.aggregate("functions", 0x40a2ce2648a26885L).target(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983094L).optional(true).ordered(true).multiple(true).origin("4657511628477196421").done();
    b.alias("canvas");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Circle", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5edL);
    b.class_(false, false, false);
    b.parent(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/4657511628476446189");
    b.version(3);
    b.property("Xpos", 0x40a2ce264896f5efL).type(PrimitiveTypeId.INTEGER).origin("4657511628476446191").done();
    b.property("Ypos", 0x40a2ce264896f5f0L).type(PrimitiveTypeId.INTEGER).origin("4657511628476446192").done();
    b.property("radius", 0x40a2ce264896f5f1L).type(PrimitiveTypeId.INTEGER).origin("4657511628476446193").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForFunction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Function", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983094L);
    b.interface_();
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/4657511628476526740");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParallelogram() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Parallelogram", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5b20f5bL);
    b.class_(false, false, false);
    b.parent(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/6332456018553999195");
    b.version(3);
    b.property("Xpos", 0x57e16732b5b20f7eL).type(PrimitiveTypeId.INTEGER).origin("6332456018553999230").done();
    b.property("Ypos", 0x57e16732b5b20f85L).type(PrimitiveTypeId.INTEGER).origin("6332456018553999237").done();
    b.property("base", 0x57e16732b5b20f8cL).type(PrimitiveTypeId.INTEGER).origin("6332456018553999244").done();
    b.property("side", 0x57e16732b5b20f96L).type(PrimitiveTypeId.INTEGER).origin("6332456018553999254").done();
    b.property("height", 0x57e16732b5b20f9dL).type(PrimitiveTypeId.INTEGER).origin("6332456018553999261").done();
    b.alias("parallelogram");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPerimeter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Perimeter", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x216bb559e4e53a18L);
    b.class_(false, false, false);
    b.parent(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983094L);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/2408217823456606744");
    b.version(3);
    b.aggregate("shape", 0x216bb559e4e53aaeL).target(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L).optional(false).ordered(true).multiple(false).origin("2408217823456606894").done();
    b.alias("perimeter");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRectangle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Rectangle", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b59aebffL);
    b.class_(false, false, false);
    b.parent(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/6332456018552482815");
    b.version(3);
    b.property("Xpos", 0x57e16732b59aec02L).type(PrimitiveTypeId.INTEGER).origin("6332456018552482818").done();
    b.property("Ypos", 0x57e16732b59aec03L).type(PrimitiveTypeId.INTEGER).origin("6332456018552482819").done();
    b.property("length", 0x57e16732b59aec04L).type(PrimitiveTypeId.INTEGER).origin("6332456018552482820").done();
    b.property("width", 0x57e16732b59aec05L).type(PrimitiveTypeId.INTEGER).origin("6332456018552482821").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRhombus() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Rhombus", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5c11b6bL);
    b.class_(false, false, false);
    b.parent(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/6332456018554985323");
    b.version(3);
    b.property("Xpos", 0x57e16732b5c11b85L).type(PrimitiveTypeId.INTEGER).origin("6332456018554985349").done();
    b.property("Ypos", 0x57e16732b5c11b8cL).type(PrimitiveTypeId.INTEGER).origin("6332456018554985356").done();
    b.property("Diagonal1", 0x57e16732b5c11b93L).type(PrimitiveTypeId.INTEGER).origin("6332456018554985363").done();
    b.property("Diagonal2", 0x57e16732b5c11ba3L).type(PrimitiveTypeId.INTEGER).origin("6332456018554985379").done();
    b.alias("rhombus");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Shape", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL);
    b.interface_();
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/4657511628476445242");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShapeInfo() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "ShapeInfo", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x216bb559e505dffeL);
    b.class_(false, false, false);
    b.parent(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983094L);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/2408217823458746366");
    b.version(3);
    b.aggregate("shape", 0x216bb559e505e02aL).target(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L).optional(false).ordered(true).multiple(false).origin("2408217823458746410").done();
    b.alias("info");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShapeRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "ShapeRef", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L);
    b.class_(false, false, false);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/4657511628476526743");
    b.version(3);
    b.associate("shape", 0x40a2ce2648983098L).target(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL).optional(false).origin("4657511628476526744").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Square", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f239L);
    b.class_(false, false, false);
    b.parent(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/4657511628476445241");
    b.version(3);
    b.property("Xpos", 0x40a2ce264896f5e9L).type(PrimitiveTypeId.INTEGER).origin("4657511628476446185").done();
    b.property("Ypos", 0x40a2ce264896f5eaL).type(PrimitiveTypeId.INTEGER).origin("4657511628476446186").done();
    b.property("sideLength", 0x40a2ce264896f5ebL).type(PrimitiveTypeId.INTEGER).origin("4657511628476446187").done();
    b.alias("square");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTrapezium() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Trapezium", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5d24a94L);
    b.class_(false, false, false);
    b.parent(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/6332456018556111508");
    b.version(3);
    b.property("Xpos", 0x57e16732b5d24ab4L).type(PrimitiveTypeId.INTEGER).origin("6332456018556111540").done();
    b.property("Ypos", 0x57e16732b5d24abbL).type(PrimitiveTypeId.INTEGER).origin("6332456018556111547").done();
    b.property("bottomBase", 0x57e16732b5d24ac5L).type(PrimitiveTypeId.INTEGER).origin("6332456018556111557").done();
    b.property("topBase", 0x57e16732b5d24ad2L).type(PrimitiveTypeId.INTEGER).origin("6332456018556111570").done();
    b.property("height", 0x57e16732b5d24aebL).type(PrimitiveTypeId.INTEGER).origin("6332456018556111595").done();
    b.alias("trapezium");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTriangle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Geometric_Lang", "Triangle", 0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5f2L);
    b.class_(false, false, false);
    b.parent(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL);
    b.origin("r:725892b5-c26c-4f56-bd6e-f00a2a2cf103(Geometric_Lang.structure)/4657511628476446194");
    b.version(3);
    b.property("Xpos", 0x40a2ce264896f5f4L).type(PrimitiveTypeId.INTEGER).origin("4657511628476446196").done();
    b.property("Ypos", 0x40a2ce264896f5f5L).type(PrimitiveTypeId.INTEGER).origin("4657511628476446197").done();
    b.property("baseLength", 0x40a2ce264896f5f6L).type(PrimitiveTypeId.INTEGER).origin("4657511628476446198").done();
    b.property("height", 0x40a2ce264896f5f8L).type(PrimitiveTypeId.INTEGER).origin("4657511628476446200").done();
    b.alias("triangle");
    return b.create();
  }
}
