package Geometric_Lang.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptorInitContext;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import jetbrains.mps.smodel.runtime.ConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SInterfaceConcept;
import org.jetbrains.mps.openapi.language.SReferenceLink;

public class ShapeRef_Constraints extends BaseConstraintsDescriptor {
  /*package*/ ShapeRef_Constraints(ConstraintsDescriptorInitContext initContext) {
    super(CONCEPTS.ShapeRef$oD, initContext);
    record(new RD1(this));
  }

  /*package*/ static final class RD1 extends BaseReferenceConstraintsDescriptor {
    /*package*/ RD1(ConstraintsDescriptor container) {
      super(LINKS.shape$qHkH, container, true, false);
    }
    @Nullable
    @Override
    public ReferenceScopeProvider getScopeProvider() {
      return ReferenceScopeProvider.fromHierarchy(CONCEPTS.Shape$UF, new SNodePointer("r:6fa2ed6d-6592-4fda-81d0-779edac7c105(Geometric_Lang.constraints)", "4657511628476709611"));
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept ShapeRef$oD = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L, "Geometric_Lang.structure.ShapeRef");
    /*package*/ static final SInterfaceConcept Shape$UF = MetaAdapterFactory.getInterfaceConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f23aL, "Geometric_Lang.structure.Shape");
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink shape$qHkH = MetaAdapterFactory.getReferenceLink(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L, 0x40a2ce2648983098L, "shape");
  }
}
