package Geometric_Lang.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import Geometric_Lang.behavior.Shape__BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import java.util.Map;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import java.util.Collection;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import org.jetbrains.mps.openapi.language.SConcept;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return "\"" + Shape__BehaviorDescriptor.getName_id42yNyp8DnyT.invoke(_context.getNode()) + "\"";
  }
  public static Object propertyMacro_GetValue_1_1(final PropertyMacroContext _context) {
    String a = "empty";

    {
      final SNode triangle = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$E1xG), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(triangle, CONCEPTS.Triangle$jg)) {
        a = "Nama : " + SPropertyOperations.getString(triangle, PROPS.name$MnvL) + " | " + "Pos : (" + SPropertyOperations.getInteger(triangle, PROPS.Xpos$xaRe) + ", " + SPropertyOperations.getInteger(triangle, PROPS.Ypos$xb6f) + ") | " + "BaseLength : " + SPropertyOperations.getInteger(triangle, PROPS.baseLength$xblg) + " | " + "Height : " + SPropertyOperations.getInteger(triangle, PROPS.height$zDtM);
      }
    }
    {
      final SNode square = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$E1xG), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(square, CONCEPTS.Square$Uc)) {
        a = "Nama : " + SPropertyOperations.getString(square, PROPS.name$MnvL) + " | " + "Pos : (" + SPropertyOperations.getInteger(square, PROPS.Xpos$tBXE) + ", " + SPropertyOperations.getInteger(square, PROPS.Ypos$tCcF) + ") | " + "sideLength : " + SPropertyOperations.getInteger(square, PROPS.sideLength$tCrG);
      }
    }
    {
      final SNode circle = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$E1xG), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(circle, CONCEPTS.Circle$6E)) {
        a = "Nama : " + SPropertyOperations.getString(circle, PROPS.name$MnvL) + " | " + "Pos : (" + SPropertyOperations.getInteger(circle, PROPS.Xpos$x9vz) + ", " + SPropertyOperations.getInteger(circle, PROPS.Ypos$x9I$) + ") | " + "Radius : " + SPropertyOperations.getInteger(circle, PROPS.radius$x9X_);
      }
    }
    {
      final SNode rectangle = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$E1xG), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(rectangle, CONCEPTS.Rectangle$mG)) {
        a = "Nama : " + SPropertyOperations.getString(rectangle, PROPS.name$MnvL) + " | " + "Pos : (" + SPropertyOperations.getInteger(rectangle, PROPS.Xpos$jGOf) + ", " + SPropertyOperations.getInteger(rectangle, PROPS.Ypos$jH3g) + ") | " + "Length : " + SPropertyOperations.getInteger(rectangle, PROPS.length$jMdA) + " | " + "Width : " + SPropertyOperations.getInteger(rectangle, PROPS.width$jMsB);
      }
    }
    {
      final SNode parallelogram = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$E1xG), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(parallelogram, CONCEPTS.Parallelogram$t_)) {
        a = "Nama : " + SPropertyOperations.getString(parallelogram, PROPS.name$MnvL) + " | " + "Pos : (" + SPropertyOperations.getInteger(parallelogram, PROPS.Xpos$W$dI) + ", " + SPropertyOperations.getInteger(parallelogram, PROPS.Ypos$W_QP) + ") | " + "Base : " + SPropertyOperations.getInteger(parallelogram, PROPS.base$WGrh) + " | " + "Side : " + SPropertyOperations.getInteger(parallelogram, PROPS.side$WNGK) + " | " + "Height : " + SPropertyOperations.getInteger(parallelogram, PROPS.height$WUhc);
      }
    }
    {
      final SNode rhombus = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$E1xG), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(rhombus, CONCEPTS.Rhombus$Jq)) {
        a = "Nama : " + SPropertyOperations.getString(rhombus, PROPS.name$MnvL) + " | " + "Pos : (" + SPropertyOperations.getInteger(rhombus, PROPS.Xpos$w8rg) + ", " + SPropertyOperations.getInteger(rhombus, PROPS.Ypos$weZG) + ") | " + "Diagonal1 : " + SPropertyOperations.getInteger(rhombus, PROPS.Diagonal1$wl$8) + " | " + "Diagonal2 : " + SPropertyOperations.getInteger(rhombus, PROPS.Diagonal2$wufH);
      }
    }
    {
      final SNode trapezium = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$E1xG), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(trapezium, CONCEPTS.Trapezium$ca)) {
        a = "Nama : " + SPropertyOperations.getString(trapezium, PROPS.name$MnvL) + " | " + "Pos : (" + SPropertyOperations.getInteger(trapezium, PROPS.Xpos$p240) + ", " + SPropertyOperations.getInteger(trapezium, PROPS.Ypos$p3H7) + ") | " + "BottomBase : " + SPropertyOperations.getInteger(trapezium, PROPS.bottomBase$paYA) + " | " + "TopBase : " + SPropertyOperations.getInteger(trapezium, PROPS.topBase$pnSt) + " | " + "Height : " + SPropertyOperations.getInteger(trapezium, PROPS.height$pBAw);
      }
    }


    return "\"" + a + "\"";
  }
  public static Object propertyMacro_GetValue_1_2(final PropertyMacroContext _context) {
    float a = 0;
    {
      final SNode triangle = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(triangle, CONCEPTS.Triangle$jg)) {
        a = SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH), CONCEPTS.Triangle$jg)), PROPS.baseLength$xblg) / 2 * SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH), CONCEPTS.Triangle$jg)), PROPS.height$zDtM);
      }
    }
    {
      final SNode square = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(square, CONCEPTS.Square$Uc)) {
        a = SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH), CONCEPTS.Square$Uc)), PROPS.sideLength$tCrG) * SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH), CONCEPTS.Square$Uc)), PROPS.sideLength$tCrG);
      }
    }
    {
      final SNode circle = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(circle, CONCEPTS.Circle$6E)) {
        a = (float) SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH), CONCEPTS.Circle$6E)), PROPS.radius$x9X_) * SPropertyOperations.getInteger(circle, PROPS.radius$x9X_) * 22 / 7;
      }
    }
    {
      final SNode rectangle = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(rectangle, CONCEPTS.Rectangle$mG)) {
        a = SPropertyOperations.getInteger(rectangle, PROPS.length$jMdA) * SPropertyOperations.getInteger(rectangle, PROPS.width$jMsB);
      }
    }
    {
      final SNode parallelogram = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(parallelogram, CONCEPTS.Parallelogram$t_)) {
        a = SPropertyOperations.getInteger(parallelogram, PROPS.base$WGrh) * SPropertyOperations.getInteger(parallelogram, PROPS.height$WUhc);
      }
    }
    {
      final SNode rhombus = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(rhombus, CONCEPTS.Rhombus$Jq)) {
        a = SPropertyOperations.getInteger(rhombus, PROPS.Diagonal1$wl$8) * SPropertyOperations.getInteger(rhombus, PROPS.Diagonal2$wufH) / 2;
      }
    }
    {
      final SNode trapezium = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(trapezium, CONCEPTS.Trapezium$ca)) {
        a = (SPropertyOperations.getInteger(trapezium, PROPS.bottomBase$paYA) + SPropertyOperations.getInteger(trapezium, PROPS.topBase$pnSt)) * SPropertyOperations.getInteger(trapezium, PROPS.height$pBAw) / 2;
      }
    }


    return "\"" + Shape__BehaviorDescriptor.getType_id5vxpNaQ1iDN.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH)) + "(" + Shape__BehaviorDescriptor.getName_id42yNyp8DnyT.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$qHnB), LINKS.shape$qHkH)) + ") " + "Area : " + String.valueOf(a) + "\"";
  }
  public static Object propertyMacro_GetValue_1_3(final PropertyMacroContext _context) {
    double a = 0;
    {
      final SNode triangle = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(triangle, CONCEPTS.Triangle$jg)) {
        a = SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH), CONCEPTS.Triangle$jg)), PROPS.baseLength$xblg) + SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH), CONCEPTS.Triangle$jg)), PROPS.height$zDtM) + Math.sqrt(SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH), CONCEPTS.Triangle$jg)), PROPS.baseLength$xblg) * SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH), CONCEPTS.Triangle$jg)), PROPS.baseLength$xblg) + SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH), CONCEPTS.Triangle$jg)), PROPS.height$zDtM) * SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH), CONCEPTS.Triangle$jg)), PROPS.height$zDtM));
      }
    }
    {
      final SNode square = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(square, CONCEPTS.Square$Uc)) {
        a = 2 * (SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH), CONCEPTS.Square$Uc)), PROPS.sideLength$tCrG) + SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH), CONCEPTS.Square$Uc)), PROPS.sideLength$tCrG));
      }
    }
    {
      final SNode circle = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(circle, CONCEPTS.Circle$6E)) {
        a = SPropertyOperations.getInteger((SNodeOperations.as(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH), CONCEPTS.Circle$6E)), PROPS.radius$x9X_) * 2 * 22 / 7;
      }
    }
    {
      final SNode rectangle = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(rectangle, CONCEPTS.Rectangle$mG)) {
        a = 2 * (SPropertyOperations.getInteger(rectangle, PROPS.length$jMdA) + SPropertyOperations.getInteger(rectangle, PROPS.width$jMsB));
      }
    }
    {
      final SNode parallelogram = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(parallelogram, CONCEPTS.Parallelogram$t_)) {
        a = 2 * (SPropertyOperations.getInteger(parallelogram, PROPS.base$WGrh) + SPropertyOperations.getInteger(parallelogram, PROPS.side$WNGK));
      }
    }
    {
      final SNode rhombus = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(rhombus, CONCEPTS.Rhombus$Jq)) {
        a = 4 * (Math.sqrt(Math.pow(SPropertyOperations.getInteger(rhombus, PROPS.Diagonal1$wl$8) / 2, 2) + Math.pow(SPropertyOperations.getInteger(rhombus, PROPS.Diagonal2$wufH) / 2, 2)));
      }
    }
    {
      final SNode trapezium = SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH);
      if (SNodeOperations.isInstanceOf(trapezium, CONCEPTS.Trapezium$ca)) {
        a = SPropertyOperations.getInteger(trapezium, PROPS.bottomBase$paYA) + SPropertyOperations.getInteger(trapezium, PROPS.topBase$pnSt) + 2 * (Math.sqrt(Math.pow((SPropertyOperations.getInteger(trapezium, PROPS.bottomBase$paYA) - SPropertyOperations.getInteger(trapezium, PROPS.topBase$pnSt)) / 2, 2) + Math.pow(SPropertyOperations.getInteger(trapezium, PROPS.height$pBAw), 2)));
      }
    }

    return "\"" + Shape__BehaviorDescriptor.getType_id5vxpNaQ1iDN.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH)) + "(" + Shape__BehaviorDescriptor.getName_id42yNyp8DnyT.invoke(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), LINKS.shape$pKb8), LINKS.shape$qHkH)) + ") " + "Perimeter : " + String.valueOf(a) + "\"";
  }
  public static Object propertyMacro_GetValue_1_4(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Iterable<SNode> sourceNodesQuery_1_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.shapes$6QPj);
  }
  public static Iterable<SNode> sourceNodesQuery_1_1(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.functions$9$sR), CONCEPTS.ShapeInfo$a8);
  }
  public static Iterable<SNode> sourceNodesQuery_1_2(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.functions$9$sR), CONCEPTS.Area$cy);
  }
  public static Iterable<SNode> sourceNodesQuery_1_3(final SourceSubstituteMacroNodesContext _context) {
    return SNodeOperations.ofConcept(SLinkOperations.getChildren(_context.getNode(), LINKS.functions$9$sR), CONCEPTS.Perimeter$j9);
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("4657511628477409989", new SNsQ(i++));
    snsqMethods.put("810646832371140578", new SNsQ(i++));
    snsqMethods.put("4657511628478473333", new SNsQ(i++));
    snsqMethods.put("2408217823456927286", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    SourceNodesQuery query = identity.forFunctionNode(snsqMethods);
    return (query != null ? query : super.getSourceNodesQuery(identity));
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_1(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_2(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_1_3(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("6332456018561469451", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x494547eeedc219b9L, 0x494547eeedc219bbL, "value"), "1.3f"));
    pvqMethods.put("810646832371140470", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x494547eeedc219b9L, 0x494547eeedc219bbL, "value"), "3.14f"));
    pvqMethods.put("4657511628478717116", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x494547eeedc219b9L, 0x494547eeedc219bbL, "value"), "3.14f"));
    pvqMethods.put("2408217823456927178", new PVQ(i++, MetaAdapterFactory.getProperty(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x494547eeedc219b9L, 0x494547eeedc219bbL, "value"), "3.14f"));
    pvqMethods.put("4657511628477262369", new PVQ(i++, MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name"), "Canvas"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    PropertyValueQuery query = identity.forTemplateNode(pvqMethods);
    return (query != null ? query : super.getPropertyValueQuery(identity));
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_1_1(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_1_2(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_1_3(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_1_4(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink shape$E1xG = MetaAdapterFactory.getContainmentLink(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x216bb559e505dffeL, 0x216bb559e505e02aL, "shape");
    /*package*/ static final SReferenceLink shape$qHkH = MetaAdapterFactory.getReferenceLink(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983097L, 0x40a2ce2648983098L, "shape");
    /*package*/ static final SContainmentLink shape$qHnB = MetaAdapterFactory.getContainmentLink(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983093L, 0x40a2ce2648983099L, "shape");
    /*package*/ static final SContainmentLink shape$pKb8 = MetaAdapterFactory.getContainmentLink(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x216bb559e4e53a18L, 0x216bb559e4e53aaeL, "shape");
    /*package*/ static final SContainmentLink shapes$6QPj = MetaAdapterFactory.getContainmentLink(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648966883L, 0x40a2ce2648a2686bL, "shapes");
    /*package*/ static final SContainmentLink functions$9$sR = MetaAdapterFactory.getContainmentLink(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648966883L, 0x40a2ce2648a26885L, "functions");
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept Triangle$jg = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5f2L, "Geometric_Lang.structure.Triangle");
    /*package*/ static final SConcept Square$Uc = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f239L, "Geometric_Lang.structure.Square");
    /*package*/ static final SConcept Circle$6E = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5edL, "Geometric_Lang.structure.Circle");
    /*package*/ static final SConcept Rectangle$mG = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b59aebffL, "Geometric_Lang.structure.Rectangle");
    /*package*/ static final SConcept Parallelogram$t_ = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5b20f5bL, "Geometric_Lang.structure.Parallelogram");
    /*package*/ static final SConcept Rhombus$Jq = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5c11b6bL, "Geometric_Lang.structure.Rhombus");
    /*package*/ static final SConcept Trapezium$ca = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5d24a94L, "Geometric_Lang.structure.Trapezium");
    /*package*/ static final SConcept ShapeInfo$a8 = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x216bb559e505dffeL, "Geometric_Lang.structure.ShapeInfo");
    /*package*/ static final SConcept Area$cy = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce2648983093L, "Geometric_Lang.structure.Area");
    /*package*/ static final SConcept Perimeter$j9 = MetaAdapterFactory.getConcept(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x216bb559e4e53a18L, "Geometric_Lang.structure.Perimeter");
  }

  private static final class PROPS {
    /*package*/ static final SProperty height$zDtM = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5f2L, 0x40a2ce264896f5f8L, "height");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty Xpos$xaRe = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5f2L, 0x40a2ce264896f5f4L, "Xpos");
    /*package*/ static final SProperty Ypos$xb6f = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5f2L, 0x40a2ce264896f5f5L, "Ypos");
    /*package*/ static final SProperty baseLength$xblg = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5f2L, 0x40a2ce264896f5f6L, "baseLength");
    /*package*/ static final SProperty Xpos$tBXE = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f239L, 0x40a2ce264896f5e9L, "Xpos");
    /*package*/ static final SProperty Ypos$tCcF = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f239L, 0x40a2ce264896f5eaL, "Ypos");
    /*package*/ static final SProperty sideLength$tCrG = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f239L, 0x40a2ce264896f5ebL, "sideLength");
    /*package*/ static final SProperty radius$x9X_ = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5edL, 0x40a2ce264896f5f1L, "radius");
    /*package*/ static final SProperty Xpos$x9vz = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5edL, 0x40a2ce264896f5efL, "Xpos");
    /*package*/ static final SProperty Ypos$x9I$ = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x40a2ce264896f5edL, 0x40a2ce264896f5f0L, "Ypos");
    /*package*/ static final SProperty width$jMsB = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b59aebffL, 0x57e16732b59aec05L, "width");
    /*package*/ static final SProperty Xpos$jGOf = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b59aebffL, 0x57e16732b59aec02L, "Xpos");
    /*package*/ static final SProperty Ypos$jH3g = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b59aebffL, 0x57e16732b59aec03L, "Ypos");
    /*package*/ static final SProperty length$jMdA = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b59aebffL, 0x57e16732b59aec04L, "length");
    /*package*/ static final SProperty height$WUhc = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5b20f5bL, 0x57e16732b5b20f9dL, "height");
    /*package*/ static final SProperty Xpos$W$dI = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5b20f5bL, 0x57e16732b5b20f7eL, "Xpos");
    /*package*/ static final SProperty Ypos$W_QP = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5b20f5bL, 0x57e16732b5b20f85L, "Ypos");
    /*package*/ static final SProperty base$WGrh = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5b20f5bL, 0x57e16732b5b20f8cL, "base");
    /*package*/ static final SProperty side$WNGK = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5b20f5bL, 0x57e16732b5b20f96L, "side");
    /*package*/ static final SProperty Diagonal2$wufH = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5c11b6bL, 0x57e16732b5c11ba3L, "Diagonal2");
    /*package*/ static final SProperty Xpos$w8rg = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5c11b6bL, 0x57e16732b5c11b85L, "Xpos");
    /*package*/ static final SProperty Ypos$weZG = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5c11b6bL, 0x57e16732b5c11b8cL, "Ypos");
    /*package*/ static final SProperty Diagonal1$wl$8 = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5c11b6bL, 0x57e16732b5c11b93L, "Diagonal1");
    /*package*/ static final SProperty height$pBAw = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5d24a94L, 0x57e16732b5d24aebL, "height");
    /*package*/ static final SProperty Xpos$p240 = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5d24a94L, 0x57e16732b5d24ab4L, "Xpos");
    /*package*/ static final SProperty Ypos$p3H7 = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5d24a94L, 0x57e16732b5d24abbL, "Ypos");
    /*package*/ static final SProperty bottomBase$paYA = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5d24a94L, 0x57e16732b5d24ac5L, "bottomBase");
    /*package*/ static final SProperty topBase$pnSt = MetaAdapterFactory.getProperty(0x943d70c59b264390L, 0xb8afcfbee654a2bcL, 0x57e16732b5d24a94L, 0x57e16732b5d24ad2L, "topBase");
  }
}
