package Geometric_Lang.sandbox;

/*Generated by MPS */


public class Test {
  public static void main(String[] args) {
    // Print infomation of shape
    System.out.println("All Shapes : ");
    System.out.println("Parallelogram");

    System.out.println("");
    System.out.println("Function : ");
    System.out.println("Nama : Parallelogram | Pos : (10, 10) | Base : 100 | Side : 10 | Height : 100");
    System.out.println("Parallelogram(Parallelogram) Area : 10000.0");
    System.out.println("Parallelogram(Parallelogram) Perimeter : 220.0");

  }
}
